name: Example CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install Dependencies
      run: |
        npm ci
    - name: Build Application
      run: |
        npm run build --if-present
  docker-build:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Hash commit
      run: echo ${{ steps.commit.outputs.short }}
    - name: Tags
      run: echo ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ steps.commit.outputs.short }}
    - name: Docker Build and Push Container
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ steps.commit.outputs.short }}
        file: ./Dockerfile
        push: true
